### ISSUE TITLE
Soldier's Pocket Medic

### ISSUE THREAD

**Issue by Sloofy** [Fedora31/nhcustom#11]
### Summary
For some reason, Soldier's Pocket Medic won't hide itself. In `database.txt`, it only specifies Heavy's file directory, to which it successfully removes Heavy's Pocket Medic. However, going through `tf_misc_dir.vpk`, I haven't found where the correct directory is for Soldier's version of the cosmetic.

**Comment by Fedora31** [comment]
I searched and eventually found the soldier's model under the name `models/player/items/soldier/fwk_soldier_pocketmedic.*`. I don't understand why they chose that name, though.
