### ISSUE TITLE
Menpo

### ISSUE THREAD

**Issue by Sloofy** [Fedora31/nhcustom#18]
### Summary
Menpo has a ton of different styles while also appearing on the Soldier, typically with the naming convention of `tw_shogun(2-4)_(CLASS).dx(80/90).vtx`. Currently, the script only accounts for style 2 of Menpo on Demo. So, the script needs to account for all 8 permutations of the cosmetic (it'll end up looking like this for demo):

- models/workshop_partner/player/items/demo/tw_shogun/tw_shogun_demo.dx80.vtx
- models/workshop_partner/player/items/demo/tw_shogun/tw_shogun_demo.dx90.vtx
- models/workshop_partner/player/items/demo/tw_shogun/tw_shogun2_demo.dx80.vtx
- models/workshop_partner/player/items/demo/tw_shogun/tw_shogun2_demo.dx90.vtx
- models/workshop_partner/player/items/demo/tw_shogun/tw_shogun3_demo.dx80.vtx
- models/workshop_partner/player/items/demo/tw_shogun/tw_shogun3_demo.dx90.vtx
- models/workshop_partner/player/items/demo/tw_shogun/tw_shogun4_demo.dx80.vtx
- models/workshop_partner/player/items/demo/tw_shogun/tw_shogun4_demo.dx90.vtx

The same is applied to Soldier with the same tw_shogun going into workshop_partner.

This is likely the last issue I'll raise for the time being. I've literally done this for every non-hat item on the Mann Co. Store, and now I am very, very tired. Thank you for your hard work.

**Comment by Fedora31** [comment]
I've pushed the changes, the issues you brought should be fixed now. Thank you for taking your time to check for problems in the database, it was really helpful.

**Comment by Sloofy** [comment]
I've got a few more cosmetics to push, but yeah keeping an eye out for this database :)
