### ISSUE TITLE
Marxman glasses do not get removed properly

### ISSUE THREAD

**Issue by Sloofy** [Fedora31/nhcustom#2]
### Summary
Due to the Marxman lacking `sd_glasses_(CLASS)_sw.vtx`, `sd_glasses_(CLASS)_cigar.dx(80/90).vtx`, `sd_glasses_(CLASS)_cigar.sw.vtx`, and its corresponding folder in `models/workshop_partner/player/items/all_class/sd_glasses`, the Marxman is not properly removed from this script.

### File directories
To make it a bit more readable, this is an example directory used for soldier on all the .VTX files needed to remove his Marxman (bolded are the files that the script makes; anything not bolded is not made and needs to be added):
- models/workshop_partner/player/items/all_class/sd_glasses/sd_glasses_soldier_cigar.dx80.vtx
- models/workshop_partner/player/items/all_class/sd_glasses/sd_glasses_soldier_cigar.dx90.vtx
- models/workshop_partner/player/items/all_class/sd_glasses/sd_glasses_soldier_cigar.sw.vtx
- models/workshop_partner/player/items/all_class/sd_glasses/sd_glasses_soldier.dx80.vtx
- models/workshop_partner/player/items/all_class/sd_glasses/sd_glasses_soldier.dx90.vtx
- models/workshop_partner/player/items/all_class/sd_glasses/sd_glasses_soldier.sw.vtx
- models/player/items/all_class/sd_glasses_soldier_cigar.dx80.vtx
- models/player/items/all_class/sd_glasses_soldier_cigar.dx90.vtx
- models/player/items/all_class/sd_glasses_soldier_cigar.sw.vtx
- **models/player/items/all_class/sd_glasses_soldier.dx80.vtx**
- **models/player/items/all_class/sd_glasses_soldier.dx90.vtx**
- models/player/items/all_class/sd_glasses_soldier.sw.vtx

**Comment by Sloofy** [comment]
After #3, I dunno how necessary it is to remove the .sw.vtx files, but might as well

**Comment by Fedora31** [comment]
Thank you for reporting those errors!
The missing files are apparently due to a mistake I made in the database, I will push the changes made to it in a moment. I'll face the other issues you reported tomorrow.

Concerning the `sw.vtx` files you mentionned, I never had to remove them to make any hats disappear and so never did, preferring not to remove files I don't know.

**Comment by Sloofy** [comment]
Gotcha! I'll go ahead and close this issue. Many thanks for getting to this so quickly!
