### ISSUE TITLE
Jungle Booty

### ISSUE THREAD

**Issue by Sloofy** [Fedora31/nhcustom#22]
### Summary
Though the Jungle Booty is in the correct location, the same file appears in workshop_partners with an almost identical file path and the same file name. Placing it in both locations is required for proper removal in-game.

- /models/workshop_partner/player/items/all_class/tr_jungle_booty/
- /models/workshop/player/items/all_class/tr_jungle_booty/ (This one exists in the database already)

**Comment by Fedora31** [comment]
I pushed the changes, tell me if there are any other issues.
